inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false
platform :ios, '9.0'

target 'DialpadView' do
  pod 'YYCategories', '~> 1.0.4'
  pod 'Masonry', '~> 1.1.0'
	pod 'HWPanModal', '~> 0.8.3'
  pod 'ReactiveObjC', '~> 3.1.1'
end

